// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD-pIGcx9jwqlzoGG9hK_qwW-VwWkpyj0',
    appId: '1:922263463677:web:d469e3ea83f8ba16850094',
    messagingSenderId: '922263463677',
    projectId: 'ageapeacts',
    authDomain: 'ageapeacts.firebaseapp.com',
    storageBucket: 'ageapeacts.appspot.com',
    measurementId: 'G-YGJYSBLPM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMSvgmev0CFw_qz2EMv_Qr67xBhYnX_i8',
    appId: '1:922263463677:android:5433f2d0612e9138850094',
    messagingSenderId: '922263463677',
    projectId: 'ageapeacts',
    storageBucket: 'ageapeacts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8EQiC78ePkRodPcIuSKgjbzuDnNCcTKU',
    appId: '1:922263463677:ios:c4eb1c2e3a433852850094',
    messagingSenderId: '922263463677',
    projectId: 'ageapeacts',
    storageBucket: 'ageapeacts.appspot.com',
    iosClientId: '922263463677-enafc3qf1385ld6f3cnh78ij7pevd6ee.apps.googleusercontent.com',
    iosBundleId: 'com.example.agepeacts',
  );
}
